### ISSUE TITLE
Fehler wenn im Adminbereich die Input Felder leer gelassen werden

### ISSUE THREAD

**Issue by c0r1an** [drthebrain/voiceserver#1]
Im Frontend kommen häßliche Fehler wenn ein Inputfeld leer gelassen wird, so doof es sich anhört aber mit sowas muss man immer rechnen. Das lässt sich leicht im Controller überprüpen ob die felder leer sind oder nicht. Siehe dazu hier https://github.com/IlchCMS/Ilch-2.0/blob/master/application/modules/war/controllers/admin/Index.php ab Zeile 84. Bei Fragen kannst du mich gerne kontaktieren, ich helfe dir falls du was nicht weisst. Mfg Thomas

**Comment by drthebrain** [comment]
Okay ich schau dann mal danach, muss erst mal arbeiten.
Normal sollte es ja genügen, die Felder als required zu kennzeichnen im HTML5, Aber besser ist ja die Eingabe nochmals PHP seitig zu checken. Recht hast du!
Da kann ich auch gleich noch ein zusätzliches Feld hinzufügen.

Required geht nicht, weil Mumble bzw. Ventrilo andere Einstellungen brauchen, wo ich dann switchen muss, erst mal schauen wie ich das dann mache
